version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_0805Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
services:
- serviceName: project.siqa_0805.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQA_0805Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2054
- serviceName: project.siqa_0805.integrations:SSL_JDBC_test
  packages:
  - name: SIQA_0805Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqa_0805.integrations:refdaf
  packages:
  - name: SIQA_0805Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
- serviceName: project.siqa_0805.referencedata:ref1
  packages:
  - name: SIQA_0805Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
- serviceName: project.siqa_0805.integrations:testhttp
  packages:
  - name: SIQA_0805Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.2054
